import { type FormEvent, useEffect, useState } from "react";
import { Link } from "react-router-dom";
import { AppLayout, type ApiError, fetchJson, formatDateOnly, formatDateTime } from "../app/core";
import { Alert, Button, Card, DataTable, FormField } from "../components/ui";

type Row={id:string;reference:string;applicantName:string|null;applicantEmail:string;applicantOrganization:string|null;submittedAt:string;validFrom:string;validUntil:string;personCount:number;pendingCount:number;approvedCount:number;rejectedCount:number;status:string};
const labels:Record<string,string>={submitted:"Offen",partially_approved:"Teilweise genehmigt",approved:"Genehmigt",rejected:"Abgelehnt"};
export function KaskdtApplicationsPage(){
  const[rows,setRows]=useState<Row[]>([]);const[total,setTotal]=useState(0);const[error,setError]=useState<string|null>(null);const[loading,setLoading]=useState(true);
  const[query,setQuery]=useState("");const[status,setStatus]=useState("");const[from,setFrom]=useState("");const[to,setTo]=useState("");
  async function load(search=""){setLoading(true);setError(null);try{const params=new URLSearchParams({page:"1",pageSize:"50",...(search?{search}:{}),...(status?{status}:{}),...(from?{from}:{}),...(to?{to}:{})});const p=await fetchJson<{applications:Row[];total:number}>(`/api/kaskdt/applications?${params}`,{headers:{}});setRows(p.applications);setTotal(p.total);}catch(e){setError((e as ApiError).message||"Die Anträge konnten nicht geladen werden.");}finally{setLoading(false);}}
  useEffect(()=>{void load();},[]);function search(e:FormEvent){e.preventDefault();void load(query.trim());}
  return <AppLayout><main className="page-panel page-shell-wide"><section className="page-hero"><h2>Anträge</h2><p>Öffentliche XLSX-Anträge prüfen und entscheiden.</p></section>{error?<Alert type="error">{error}</Alert>:null}<Card>
    <form className="filter-grid" onSubmit={search}><FormField label="Suche"><input value={query} onChange={(e)=>setQuery(e.target.value)} placeholder="Referenz, Antragsteller, E-Mail oder Besucher"/></FormField><FormField label="Status"><select value={status} onChange={(e)=>setStatus(e.target.value)}><option value="">Alle</option><option value="open">Offen</option><option value="partially_approved">Teilweise entschieden</option><option value="approved">Genehmigt</option><option value="rejected">Abgelehnt</option></select></FormField><FormField label="Zeitraum von"><input type="date" value={from} onChange={(e)=>setFrom(e.target.value)}/></FormField><FormField label="Zeitraum bis"><input type="date" value={to} onChange={(e)=>setTo(e.target.value)}/></FormField><Button type="submit" disabled={loading}>Filter anwenden</Button></form>
    <p>{total} Anträge</p><DataTable><thead><tr><th>Referenz</th><th>Antragsteller</th><th>Eingang</th><th>Zeitraum</th><th>Personen</th><th>Entscheidungen</th><th>Status</th><th>Aktion</th></tr></thead><tbody>{rows.map((row)=><tr key={row.id}><td><strong>{row.reference}</strong></td><td>{row.applicantName||"–"}<br/><small className="break-anywhere">{row.applicantEmail}</small><br/><small>{row.applicantOrganization||"–"}</small></td><td>{formatDateTime(row.submittedAt)}</td><td>{formatDateOnly(row.validFrom)} – {formatDateOnly(row.validUntil)}</td><td>{row.personCount}</td><td>{row.pendingCount} offen · {row.approvedCount} genehmigt · {row.rejectedCount} abgelehnt</td><td><span className={`badge ${row.status}`}>{labels[row.status]||row.status}</span></td><td><Link className="button-link" to={`/kaskdt/antraege/${row.id}`}>Prüfen</Link></td></tr>)}{!loading&&!rows.length?<tr><td colSpan={8}>Keine Anträge gefunden.</td></tr>:null}{loading?<tr><td colSpan={8}>Anträge werden geladen …</td></tr>:null}</tbody></DataTable>
  </Card></main></AppLayout>;
}
