import { useEffect, useMemo, useState } from "react";
import { Link, useParams } from "react-router-dom";
import { AppLayout, type ApiError, fetchJson, formatDateOnly, formatDateTime } from "../app/core";
import { Alert, Button, Card, DataTable, FormField } from "../components/ui";

type Entry={id:string;rowNumber:number;firstName:string|null;lastName:string|null;company:string|null;nationalityCode:string|null;birthDate:string|null;phone:string|null;email:string|null;licensePlate:string|null;gateName:string;hostName:string|null;hostPhone:string|null;hostEmail:string|null;hostDepartment:string|null;purpose:string|null;validFrom:string;validUntil:string;notes:string|null;status:"pending"|"approved"|"rejected";rejectionReason:string|null;createdVisitId:string|null;version:string};
type Application={id:string;reference:string;applicantEmail:string;applicantName:string|null;applicantOrganization:string|null;applicantNote:string|null;status:string;submittedAt:string;finalizedAt:string|null;version:string;entries:Entry[]};
export function KaskdtApplicationDetailPage(){const{id=""}=useParams();const[application,setApplication]=useState<Application|null>(null);const[selected,setSelected]=useState<Set<string>>(new Set());const[reason,setReason]=useState("");const[error,setError]=useState<string|null>(null);const[message,setMessage]=useState<string|null>(null);const[busy,setBusy]=useState(false);
  async function load(){setError(null);try{setApplication(await fetchJson<Application>(`/api/kaskdt/applications/${id}`,{headers:{}}));setSelected(new Set());}catch(e){setError((e as ApiError).message||"Der Antrag konnte nicht geladen werden.");}}
  useEffect(()=>{void load();},[id]);const pending=useMemo(()=>application?.entries.filter((e)=>e.status==="pending")??[],[application]);const approved=application?.entries.filter((e)=>e.status==="approved").length??0;const rejected=application?.entries.filter((e)=>e.status==="rejected").length??0;
  async function decide(decision:"approved"|"rejected",allPending=false,ids?:string[]){if(!application)return;if(decision==="rejected"&&!reason.trim()){setError("Bitte geben Sie einen Ablehnungsgrund an.");return;}setBusy(true);setError(null);setMessage(null);try{const updated=await fetchJson<Application>(`/api/kaskdt/applications/${id}/decisions`,{method:"POST",body:JSON.stringify({decision,rejectionReason:decision==="rejected"?reason.trim():undefined,applicationVersion:application.version,allPending,entryIds:allPending?undefined:(ids??[...selected])})});setApplication(updated);setSelected(new Set());setReason("");setMessage("Entscheidung gespeichert. Der Antragsteller wird erst bei der Finalisierung informiert.");}catch(e){setError((e as ApiError).message||"Die Entscheidung konnte nicht gespeichert werden.");}finally{setBusy(false);}}
  async function finalize(){if(!application)return;setBusy(true);setError(null);try{const updated=await fetchJson<Application>(`/api/kaskdt/applications/${id}/finalize`,{method:"POST",body:JSON.stringify({applicationVersion:application.version})});setApplication(updated);setMessage("Entscheidung abgeschlossen. Die zusammenfassende E-Mail wurde zur Zustellung vorgemerkt.");}catch(e){setError((e as ApiError).message||"Die Entscheidung konnte nicht abgeschlossen werden.");}finally{setBusy(false);}}
  async function retryMails(){setBusy(true);setError(null);try{const result=await fetchJson<{message:string}>(`/api/kaskdt/applications/${id}/retry-mails`,{method:"POST",body:"{}"});setMessage(result.message);}catch(e){setError((e as ApiError).message||"Die E-Mail-Zustellung konnte nicht erneut verarbeitet werden.");}finally{setBusy(false);}}
  return <AppLayout><main className="page-panel page-shell-wide"><Link to="/kaskdt/antraege">← Zur Antragsübersicht</Link>{error?<Alert type="error">{error} {error.includes("zwischenzeitlich")?<Button onClick={()=>void load()}>Neu laden</Button>:null}</Alert>:null}{message?<Alert type="success">{message}</Alert>:null}{!application?<Card><p>Antrag wird geladen …</p></Card>:<><section className="page-hero"><h2>Antrag {application.reference}</h2><p>{pending.length} offen · {approved} genehmigt · {rejected} abgelehnt</p></section><Card><h3>Antrag</h3><dl className="detail-grid"><div><dt>Antragsteller</dt><dd>{application.applicantName||"–"}</dd></div><div><dt>E-Mail</dt><dd className="break-anywhere">{application.applicantEmail}</dd></div><div><dt>Organisation</dt><dd>{application.applicantOrganization||"–"}</dd></div><div><dt>Eingang</dt><dd>{formatDateTime(application.submittedAt)}</dd></div><div><dt>Status</dt><dd>{application.status}</dd></div><div><dt>Personen</dt><dd>{application.entries.length}</dd></div><div className="detail-wide"><dt>Bemerkung</dt><dd>{application.applicantNote||"–"}</dd></div></dl></Card>
    <Card><div className="section-header"><div><h3>Personen</h3><p>Ausgewählt: {selected.size}</p></div></div><DataTable><thead><tr><th>Auswahl</th><th>Zeile</th><th>Person</th><th>Besuch</th><th>Ansprechpartner</th><th>Weitere Angaben</th><th>Status / Grund</th><th>Aktion</th></tr></thead><tbody>{application.entries.map((entry)=><tr key={entry.id}><td>{entry.status==="pending"?<input type="checkbox" aria-label={`Zeile ${entry.rowNumber} auswählen`} checked={selected.has(entry.id)} onChange={(e)=>setSelected((current)=>{const next=new Set(current);e.target.checked?next.add(entry.id):next.delete(entry.id);return next;})}/>:"–"}</td><td>{entry.rowNumber}</td><td>{[entry.firstName,entry.lastName].filter(Boolean).join(" ")||"–"}<br/><small>{entry.company||"–"} · {entry.nationalityCode||"–"}</small></td><td>{formatDateOnly(entry.validFrom)} – {formatDateOnly(entry.validUntil)}<br/><small>{entry.gateName} · {entry.purpose||"–"}</small></td><td>{entry.hostName||"–"}<br/><small>{entry.hostDepartment||"–"}</small></td><td>{entry.licensePlate||"–"}<br/><small>{entry.phone||entry.email||"–"}</small></td><td><span className={`badge ${entry.status}`}>{entry.status==="pending"?"Offen":entry.status==="approved"?"Genehmigt":"Abgelehnt"}</span>{entry.rejectionReason?<div>{entry.rejectionReason}</div>:null}</td><td>{entry.status==="pending"?<div className="form-actions"><Button disabled={busy} onClick={()=>void decide("approved",false,[entry.id])}>Genehmigen</Button><Button disabled={busy||!reason.trim()} onClick={()=>void decide("rejected",false,[entry.id])}>Ablehnen</Button></div>:entry.createdVisitId?<Link to={`/kaskdt/besucher/${entry.createdVisitId}`}>Visit öffnen</Link>:"–"}</td></tr>)}</tbody></DataTable>
    {pending.length?<div className="decision-actions"><FormField label="Ablehnungsgrund"><textarea value={reason} onChange={(e)=>setReason(e.target.value)} rows={3} maxLength={1000}/></FormField><div className="form-actions"><Button disabled={busy||selected.size===0} onClick={()=>void decide("approved")}>Auswahl genehmigen</Button><Button disabled={busy||selected.size===0||!reason.trim()} onClick={()=>void decide("rejected")}>Auswahl ablehnen</Button><Button disabled={busy} onClick={()=>window.confirm(`Sie genehmigen ${pending.length} Personen. Möchten Sie fortfahren?`)&&void decide("approved",true)}>Alle offenen Personen genehmigen</Button><Button disabled={busy||!reason.trim()} onClick={()=>window.confirm(`Sie lehnen ${pending.length} Personen ab. Möchten Sie fortfahren?`)&&void decide("rejected",true)}>Alle offenen Personen ablehnen</Button></div></div>:null}
    {!pending.length&&!application.finalizedAt?<div className="finalize-panel"><h3>Entscheidung abschließen und E-Mail senden</h3><p>{approved} genehmigt · {rejected} abgelehnt · Empfänger: {application.applicantEmail}</p><Button disabled={busy} onClick={()=>void finalize()}>{busy?"Wird abgeschlossen …":"Entscheidung abschließen und E-Mail senden"}</Button></div>:null}{application.finalizedAt?<Alert type="info">Finalisiert am {formatDateTime(application.finalizedAt)}. <Button disabled={busy} onClick={()=>void retryMails()}>E-Mail-Zustellung erneut prüfen</Button></Alert>:null}</Card></>}</main></AppLayout>;
}
