import { useEffect, useState, type FormEvent } from "react";
import { Link } from "react-router-dom";
import { AppLayout, type ApiError, fetchJson, formatDateOnly } from "../app/core";
import { Alert, Card, FormField } from "../components/ui";

type ImportSuccess={requestNumber:string;token:string;visitorCount:number;status:string;statusUrl:string;message:string};
type PublicStatus={requestNumber:string;status:string;createdAt:string;entries:Array<{id:string;firstName:string;lastName:string;company:string;nationalityName?:string;status:string;finalValidFrom:string|null;finalValidUntil:string|null;rejectionReason:string|null;barracksAreaName:string;gateName:string|null}>};
const labels:Record<string,string>={pending:"Offen",partially_approved:"Teilweise bearbeitet",approved:"Genehmigt",rejected:"Abgelehnt",completed:"Abgeschlossen",revoked:"Widerrufen"};

export function PublicSimplifiedRegistrationPage({statusOnly=false}:{statusOnly?:boolean}){
  const [csrfToken,setCsrfToken]=useState(""); const [file,setFile]=useState<File|null>(null); const [email,setEmail]=useState("");
  const [loading,setLoading]=useState(false); const [error,setError]=useState<string|null>(null); const [success,setSuccess]=useState<ImportSuccess|null>(null);
  const [requestNumber,setRequestNumber]=useState(""); const [token,setToken]=useState(""); const [status,setStatus]=useState<PublicStatus|null>(null);
  useEffect(()=>{void fetchJson<{csrfToken:string}>("/api/public/simplified-registration/bootstrap",{method:"GET",headers:{}}).then((p)=>setCsrfToken(p.csrfToken)).catch((e:ApiError)=>setError(e.message||"Seite konnte nicht geladen werden."));},[]);
  async function submitImport(event:FormEvent){event.preventDefault();if(!file)return;setLoading(true);setError(null);try{const body=new FormData();body.set("file",file);body.set("applicantEmail",email);const result=await fetchJson<ImportSuccess>("/api/public/simplified-registration/import",{method:"POST",headers:{"X-CSRF-Token":csrfToken},body});setSuccess(result);setRequestNumber(result.requestNumber);setToken(result.token);}catch(e){setError((e as ApiError).message||"Excel-Datei konnte nicht importiert werden.");}finally{setLoading(false);}}
  async function queryStatus(event:FormEvent){event.preventDefault();setLoading(true);setError(null);try{setStatus(await fetchJson<PublicStatus>("/api/public/simplified-registration/status",{method:"POST",headers:{"X-CSRF-Token":csrfToken},body:JSON.stringify({requestNumber,token})}));}catch(e){setStatus(null);setError((e as ApiError).message||"Status konnte nicht geladen werden.");}finally{setLoading(false);}}
  return <AppLayout><main className="page-panel page-shell-wide"><section className="page-hero"><div className="page-hero-content"><h2>{statusOnly?"Status der vereinfachten Anmeldung":"Vereinfachte Besucheranmeldung"}</h2><p>Externe Personen gemeinsam per Excel anmelden. Jede Person wird anschließend durch den Kasernenkommandanten geprüft.</p></div></section>
    {error?<Alert type="error">{error}</Alert>:null}
    {!statusOnly?<Card><div className="section-header"><h3>Excel-Anmeldung einreichen</h3></div><ol><li>Eigene Vorlage herunterladen.</li><li>Daten ab Zeile 4 eintragen.</li><li>Datei hochladen und Zugangsdaten sicher aufbewahren.</li></ol><div className="row-actions"><a className="button-link" href="/api/public/simplified-registration/template">Excel-Vorlage herunterladen</a></div><form onSubmit={submitImport}><div className="form-grid two-columns"><FormField label="E-Mail des Antragstellers" required><input type="email" required value={email} onChange={(e)=>setEmail(e.target.value)}/></FormField><FormField label="Excel-Datei" required><input type="file" required accept=".xlsx,application/vnd.openxmlformats-officedocument.spreadsheetml.sheet" onChange={(e)=>setFile(e.target.files?.[0]??null)}/></FormField></div><div className="row-actions"><button disabled={loading||!csrfToken||!file}>{loading?"Wird importiert …":"Anmeldung einreichen"}</button></div></form></Card>:null}
    {success?<Alert type="success"><strong>{success.message}</strong><br/>Vorgangsnummer: <code>{success.requestNumber}</code><br/>Sicherheitstoken: <code>{success.token}</code><br/>{success.visitorCount} Besucher wurden übernommen. Vorgangsnummer und Token werden zusätzlich per E-Mail verschickt.<br/><Link to="/vereinfachte-besucheranmeldung/status">Öffentliche Statusabfrage öffnen</Link></Alert>:null}
    <Card><div className="section-header"><h3>Status abfragen</h3></div><form onSubmit={queryStatus}><div className="form-grid two-columns"><FormField label="Vorgangsnummer" required><input required autoComplete="off" value={requestNumber} onChange={(e)=>setRequestNumber(e.target.value.toUpperCase())} placeholder="VM-2026-000123"/></FormField><FormField label="Sicherheitstoken" required><input required autoComplete="off" value={token} onChange={(e)=>setToken(e.target.value)}/></FormField></div><div className="row-actions"><button disabled={loading||!csrfToken}>{loading?"Wird geprüft …":"Status anzeigen"}</button></div></form></Card>
    {status?<Card><div className="section-header"><h3>{status.requestNumber}</h3><span className={`status-badge status-${status.status}`}>{labels[status.status]??status.status}</span></div><div className="table-wrap"><table className="data-table"><thead><tr><th>Besucher</th><th>Firma</th><th>Status</th><th>Genehmigter Zeitraum</th><th>Kasernenbereich / Wache</th><th>Hinweis</th></tr></thead><tbody>{status.entries.map((entry)=><tr key={entry.id}><td>{entry.firstName} {entry.lastName}</td><td>{entry.company}</td><td>{labels[entry.status]??entry.status}</td><td>{entry.finalValidFrom?`${formatDateOnly(entry.finalValidFrom)} – ${formatDateOnly(entry.finalValidUntil)}`:"Noch nicht festgelegt"}</td><td>{entry.barracksAreaName}{entry.gateName?` / ${entry.gateName}`:""}</td><td>{entry.rejectionReason||"-"}</td></tr>)}</tbody></table></div></Card>:null}
  </main></AppLayout>;
}
