import { type FormEvent, useEffect, useRef, useState } from "react";
import { AppLayout, type ApiError, fetchJson } from "../app/core";
import { Alert, Button, Card, DataTable, FormField } from "../components/ui";

type PreviewRow={rowNumber:number;firstName:string|null;lastName:string|null;company:string|null;validFrom:string|null;validUntil:string|null;gateName:string|null;hostName:string|null;hostDepartment:string|null;licensePlate:string|null;warnings:string[];errors:string[]};
type Preview={rows:PreviewRow[];valid:boolean;ignoredSampleRows:number};

export function PublicSimplifiedApplicationPage(){
  const [csrf,setCsrf]=useState("");const[file,setFile]=useState<File|null>(null);const[preview,setPreview]=useState<Preview|null>(null);const[busy,setBusy]=useState<"preview"|"submit"|null>(null);const[error,setError]=useState<string|null>(null);const[result,setResult]=useState<{reference:string;status:string;emailVerificationRequired:boolean}|null>(null);const fileRef=useRef<HTMLInputElement>(null);
  useEffect(()=>{void fetchJson<{csrfToken:string}>("/api/public/simplified-applications/bootstrap",{headers:{}}).then((p)=>setCsrf(p.csrfToken)).catch(()=>setError("Die Antragsseite konnte nicht vorbereitet werden. Bitte laden Sie die Seite neu."));},[]);
  async function upload(path:string,form:FormData){return fetchJson<any>(path,{method:"POST",headers:{"X-CSRF-Token":csrf},body:form});}
  async function inspect(){if(!file)return setError("Bitte wählen Sie zuerst eine XLSX-Datei aus.");setBusy("preview");setError(null);setResult(null);try{const form=new FormData();form.append("file",file);setPreview(await upload("/api/public/simplified-applications/preview",form));}catch(e){const api=e as ApiError;setPreview(null);setError(api.message||"Die Datei konnte nicht gelesen werden. Bitte verwenden Sie die aktuelle XLSX-Vorlage.");}finally{setBusy(null);}}
  async function submit(event:FormEvent<HTMLFormElement>){event.preventDefault();if(!file||!preview?.valid)return setError("Bitte prüfen und korrigieren Sie die Datei vor dem Absenden.");setBusy("submit");setError(null);const data=new FormData(event.currentTarget);data.set("file",file);try{const created=await upload("/api/public/simplified-applications",data);setResult(created);setPreview(null);event.currentTarget.reset();setFile(null);}catch(e){const api=e as ApiError;setError(api.message||"Der Antrag konnte nicht eingereicht werden.");}finally{setBusy(null);}}
  return <AppLayout><main className="page-panel page-shell-wide public-xlsx-page"><section className="page-hero"><h2>Besucherantrag per XLSX</h2><p>Reichen Sie mehrere Besucher ohne Benutzerkonto sicher zur Prüfung ein.</p></section>
    <ol className="application-steps" aria-label="Ablauf"><li>Vorlage herunterladen</li><li>Datei ausfüllen</li><li>Datei hochladen</li><li>Daten prüfen</li><li>Antrag absenden</li></ol>
    {error?<Alert type="error"><span role="alert">{error}</span></Alert>:null}{result?<Alert type="success"><strong>Antrag {result.reference} wurde erfasst.</strong><br/>{result.emailVerificationRequired?"Bitte bestätigen Sie jetzt Ihre E-Mail-Adresse über die zugesandte Nachricht.":"Der Antrag wurde an KSKdt zur Prüfung weitergeleitet."}</Alert>:null}
    <div className="split-card-grid"><Card><h3>1. Vorlage vorbereiten</h3><p>Wache sowie Gültig-von/-bis sind notwendig. Personen- und Kontaktdaten dürfen leer bleiben.</p><a className="button-link" href="/api/public/simplified-applications/template.xlsx" download>XLSX-Vorlage herunterladen</a></Card>
    <Card><h3>2. Datei prüfen</h3><FormField label="Ausgefüllte XLSX-Datei" required><input ref={fileRef} type="file" accept=".xlsx,application/vnd.openxmlformats-officedocument.spreadsheetml.sheet" onChange={(e)=>{setFile(e.target.files?.[0]??null);setPreview(null);}}/></FormField><Button type="button" onClick={()=>void inspect()} disabled={!csrf||!file||Boolean(busy)}>{busy==="preview"?"Datei wird geprüft …":"Datei prüfen und Vorschau anzeigen"}</Button><p className="form-help">Maximal 5 MB, 500 Personen und 3 Tabellenblätter. Makros und Formeln sind nicht erlaubt.</p></Card></div>
    {preview?<Card><div className="section-header"><div><h3>3. Vorschau</h3><p>{preview.rows.length} erkannte Personen · {preview.valid?"bereit zum Absenden":"bitte Fehler in der XLSX korrigieren"}</p></div></div><DataTable><thead><tr><th>Zeile</th><th>Besucher</th><th>Firma</th><th>Zeitraum</th><th>Wache</th><th>Ansprechpartner / Bereich</th><th>Kennzeichen</th><th>Prüfung</th></tr></thead><tbody>{preview.rows.map((row)=><tr key={row.rowNumber}><td>{row.rowNumber}</td><td>{[row.firstName,row.lastName].filter(Boolean).join(" ")||"–"}</td><td>{row.company||"–"}</td><td>{row.validFrom||"–"} – {row.validUntil||"–"}</td><td>{row.gateName||"–"}</td><td>{row.hostName||"–"}<br/><small>{row.hostDepartment||"–"}</small></td><td>{row.licensePlate||"–"}</td><td>{row.errors.map((x)=><div className="field-error" key={x}>{x}</div>)}{row.warnings.map((x)=><div className="warning-text" key={x}>{x}</div>)}{!row.errors.length&&!row.warnings.length?"Gültig":null}</td></tr>)}</tbody></DataTable></Card>:null}
    {preview?.valid?<Card><h3>4. Antragsteller und Absenden</h3><form className="form-grid" onSubmit={(event)=>void submit(event)}><FormField label="Ihre E-Mail-Adresse" required><input name="applicantEmail" type="email" autoComplete="email" required maxLength={255}/></FormField><FormField label="Ihr Name (optional)"><input name="applicantName" autoComplete="name" maxLength={255}/></FormField><FormField label="Organisation / Abteilung (optional)"><input name="applicantOrganization" maxLength={255}/></FormField><FormField label="Bemerkung (optional)"><textarea name="applicantNote" maxLength={2000} rows={4}/></FormField><div className="form-actions"><Button type="submit" disabled={Boolean(busy)}>{busy==="submit"?"Antrag wird eingereicht …":"Antrag verbindlich absenden"}</Button></div></form></Card>:null}
  </main></AppLayout>;
}
