import crypto from "node:crypto";
import { Router, type Request, type Response } from "express";
import multer, { MulterError } from "multer";
import { z } from "zod";
import { writeAuditLog } from "../lib/auditLog";
import { writeErrorLog } from "../lib/errorLogs";
import { checkRateLimit } from "../lib/rateLimit";
import { createPublicSimplifiedApplication, decideApplicationEntries, deliverApplicationMailOutbox, finalizeApplication, getKaskdtApplication, listKaskdtApplications, PublicApplicationError, verifyPublicSimplifiedApplication } from "../lib/publicSimplifiedApplications";
import { parseAndValidatePublicApplicationXlsx, PUBLIC_XLSX_LIMITS, PublicXlsxError } from "../lib/publicSimplifiedXlsx";
import { buildSimplifiedImportTemplate } from "../lib/simplifiedImportTemplate";
import { listActiveGates } from "../lib/publicPreRegistrations";
import { loadSystemSettings, upsertSystemSettings, WORKFLOW_SETTING_KEYS } from "../lib/systemSettings";
import { getRequestIp, getRequestUserAgent, handleUnexpectedError, hasValidCsrfToken, issueCsrfToken, requireRole, sendError, sendValidationError } from "./shared";

export const publicSimplifiedApplicationsRouter = Router();
const upload = multer({ storage:multer.memoryStorage(), limits:{fileSize:PUBLIC_XLSX_LIMITS.maxBytes,files:1,fields:8} });
const applicantSchema=z.object({applicantEmail:z.string().trim().toLowerCase().email("Bitte geben Sie eine gültige E-Mail-Adresse ein.").max(255),applicantName:z.string().trim().max(255).optional().or(z.literal("")),applicantOrganization:z.string().trim().max(255).optional().or(z.literal("")),applicantNote:z.string().trim().max(2000).optional().or(z.literal("")),clientRequestId:z.string().uuid().optional()}).strict();
const settingSchema=z.object({requireEmailVerification:z.boolean()}).strict();
const listSchema=z.object({status:z.enum(["open","submitted","partially_approved","approved","rejected"]).optional(),search:z.string().trim().max(200).optional(),from:z.string().regex(/^\d{4}-\d{2}-\d{2}$/).optional(),to:z.string().regex(/^\d{4}-\d{2}-\d{2}$/).optional(),page:z.coerce.number().int().min(1).default(1),pageSize:z.coerce.number().int().min(1).max(100).default(25)});
const rowVersionSchema=z.string().regex(/^(?:0x)?[0-9a-f]{16}$/i);
const decisionSchema=z.object({decision:z.enum(["approved","rejected"]),rejectionReason:z.string().trim().max(1000).optional().or(z.literal("")),applicationVersion:rowVersionSchema,entryIds:z.array(z.string().uuid()).min(1).max(PUBLIC_XLSX_LIMITS.maxRows).optional(),allPending:z.boolean().optional()}).strict().superRefine((value,ctx)=>{if(value.decision==="rejected"&&!value.rejectionReason)ctx.addIssue({code:z.ZodIssueCode.custom,path:["rejectionReason"],message:"Bitte geben Sie einen Ablehnungsgrund an."});if(!value.allPending&&!value.entryIds?.length)ctx.addIssue({code:z.ZodIssueCode.custom,path:["entryIds"],message:"Bitte wählen Sie mindestens eine Person aus."});});
const finalizeSchema=z.object({applicationVersion:rowVersionSchema}).strict();

function secure(response:Response){response.setHeader("Cache-Control","no-store, max-age=0");response.setHeader("Pragma","no-cache");response.setHeader("Referrer-Policy","no-referrer");}
function rate(request:Request,response:Response,kind:string,limit:number,fingerprint="anonymous"){const decision=checkRateLimit(`public-xlsx:${kind}:${getRequestIp(request)}:${fingerprint}`,limit,60);if(!decision.allowed){response.setHeader("Retry-After",String(decision.retryAfterSeconds));sendError(response,429,"RATE_LIMITED","Zu viele Anfragen. Bitte versuchen Sie es später erneut.");return false;}return true;}
function requireCsrf(request:Request,response:Response){if(!hasValidCsrfToken(request)){sendError(response,403,"CSRF_INVALID","Die Formularsitzung ist abgelaufen. Bitte laden Sie die Seite neu.");return false;}return true;}
function receiveFile(request:Request,response:Response,next:(file:Express.Multer.File)=>Promise<unknown>){return upload.single("file")(request,response,(error)=>{if(error){if(error instanceof MulterError&&error.code==="LIMIT_FILE_SIZE")return sendError(response,400,"FILE_TOO_LARGE","Die Datei ist größer als 5 MB.");return sendError(response,400,"UPLOAD_ERROR","Die Datei konnte nicht gelesen werden.");}const file=request.file;if(!file)return sendValidationError(response,{fieldErrors:{file:["Bitte wählen Sie eine XLSX-Datei aus."]}});if(!file.originalname.toLowerCase().endsWith(".xlsx")||file.originalname.toLowerCase().endsWith(".xlsm"))return sendError(response,400,"INVALID_FILE_TYPE","Es werden ausschließlich XLSX-Dateien ohne Makros unterstützt.");void next(file);});}
function handleKnown(response:Response,error:unknown){if(error instanceof PublicXlsxError)return sendError(response,400,error.code,error.message);if(error instanceof PublicApplicationError){if(error.reason==="not_found")return sendError(response,404,"APPLICATION_NOT_FOUND","Der Antrag wurde nicht gefunden.");if(error.reason==="expired")return sendError(response,410,"VERIFICATION_EXPIRED","Dieser Bestätigungslink ist abgelaufen.");if(error.reason==="revoked")return sendError(response,410,"VERIFICATION_REVOKED","Dieser Bestätigungslink wurde widerrufen.");if(error.reason==="conflict")return sendError(response,409,"APPLICATION_CONFLICT","Der Antrag wurde zwischenzeitlich geändert. Bitte laden Sie die aktuellen Daten neu.");if(error.reason==="not_ready")return sendError(response,409,"APPLICATION_NOT_READY","Die Aktion kann im aktuellen Bearbeitungsstand nicht ausgeführt werden.");if(error.reason==="mail_unavailable"){const cause=error.cause instanceof Error?error.cause:error;console.error(cause);void writeErrorLog({errorCode:"PUBLIC_XLSX_VERIFICATION_MAIL_FAILED",message:cause.message,requestPath:response.req?.originalUrl??null,requestMethod:response.req?.method??null,ipAddress:response.req?getRequestIp(response.req):null,userAgent:response.req?getRequestUserAgent(response.req):null,stackTrace:cause.stack??null,metadataJson:JSON.stringify({action:"PUBLIC_XLSX_SUBMIT",result:"failure",stage:"verification_mail"}),requestId:response.req?.requestId??null}).catch((loggingError)=>console.error("error log write failed",loggingError));return sendError(response,503,"VERIFICATION_MAIL_FAILED","Der Antrag konnte derzeit nicht vollständig verarbeitet werden. Bitte versuchen Sie es später erneut.");}}return null;}

publicSimplifiedApplicationsRouter.get("/api/public/simplified-applications/bootstrap",async(request,response)=>{secure(response);if(!rate(request,response,"bootstrap",60))return;try{const settings=await loadSystemSettings([WORKFLOW_SETTING_KEYS.publicXlsxRequireEmailVerification]);response.json({csrfToken:issueCsrfToken(response),limits:{maxBytes:PUBLIC_XLSX_LIMITS.maxBytes,maxRows:PUBLIC_XLSX_LIMITS.maxRows,maxSheets:PUBLIC_XLSX_LIMITS.maxSheets},requireEmailVerification:settings.get(WORKFLOW_SETTING_KEYS.publicXlsxRequireEmailVerification)!=="false"});}catch(error){return handleUnexpectedError(response,error,"PUBLIC_XLSX_BOOTSTRAP_FAILED","Die Antragsseite konnte nicht vorbereitet werden.");}});
publicSimplifiedApplicationsRouter.get("/api/public/simplified-applications/template.xlsx",async(request,response)=>{secure(response);if(!rate(request,response,"template",60))return;try{const buffer=await buildSimplifiedImportTemplate(await listActiveGates());response.type("application/vnd.openxmlformats-officedocument.spreadsheetml.sheet").setHeader("Content-Disposition",'attachment; filename="vereinfachte-besucherregelung-vorlage.xlsx"');return response.send(buffer);}catch(error){return handleUnexpectedError(response,error,"TEMPLATE_FAILED","Die XLSX-Vorlage konnte nicht erstellt werden.");}});
publicSimplifiedApplicationsRouter.post("/api/public/simplified-applications/preview",(request,response)=>{secure(response);if(!rate(request,response,"preview",10)||!requireCsrf(request,response))return;return receiveFile(request,response,async(file)=>{try{const preview=await parseAndValidatePublicApplicationXlsx(file.buffer);await writeAuditLog({user:"public-xlsx-applicant",action:"PUBLIC_XLSX_APPLICATION_PREVIEWED",objectType:"public_simplified_application",objectId:"preview",ipAddress:getRequestIp(request),userAgent:getRequestUserAgent(request),metadata:{row_count:preview.rows.length,valid:preview.valid,invalid_rows:preview.rows.filter((row)=>row.errors.length).length}});response.json(preview);}catch(error){if(handleKnown(response,error))return;handleUnexpectedError(response,error,"XLSX_PREVIEW_FAILED","Die Datei konnte nicht geprüft werden.");}});});
publicSimplifiedApplicationsRouter.post("/api/public/simplified-applications",(request,response)=>{secure(response);if(!rate(request,response,"submit",5)||!requireCsrf(request,response))return;return receiveFile(request,response,async(file)=>{try{const applicant=applicantSchema.safeParse(request.body);if(!applicant.success)return sendValidationError(response,{fieldErrors:applicant.error.flatten().fieldErrors});const preview=await parseAndValidatePublicApplicationXlsx(file.buffer);if(!preview.valid)return sendError(response,400,"XLSX_ROWS_INVALID","Der Antrag enthält fehlerhafte Zeilen.",{rows:preview.rows});const settings=await loadSystemSettings([WORKFLOW_SETTING_KEYS.publicXlsxRequireEmailVerification]);const required=settings.get(WORKFLOW_SETTING_KEYS.publicXlsxRequireEmailVerification)!=="false";const result=await createPublicSimplifiedApplication({email:applicant.data.applicantEmail,name:applicant.data.applicantName,organization:applicant.data.applicantOrganization,note:applicant.data.applicantNote,clientRequestId:applicant.data.clientRequestId},preview.rows,required,{ip:getRequestIp(request),userAgent:getRequestUserAgent(request)});response.status(201).json(result);}catch(error){if(handleKnown(response,error))return;handleUnexpectedError(response,error,"PUBLIC_XLSX_SUBMIT_FAILED","Der Antrag konnte derzeit nicht vollständig verarbeitet werden. Bitte versuchen Sie es später erneut.");}});});
publicSimplifiedApplicationsRouter.post("/api/public/simplified-applications/verify",async(request,response)=>{secure(response);const token=request.get("x-application-verification-token")?.trim()??"";const fingerprint=token?crypto.createHash("sha256").update(token).digest("hex").slice(0,16):"invalid";if(!rate(request,response,"verify",12,fingerprint))return;try{return response.json(await verifyPublicSimplifiedApplication(token,{ip:getRequestIp(request),userAgent:getRequestUserAgent(request)}));}catch(error){if(handleKnown(response,error))return;return handleUnexpectedError(response,error,"EMAIL_VERIFICATION_FAILED","Ihre E-Mail-Adresse konnte nicht bestätigt werden.");}});

publicSimplifiedApplicationsRouter.get("/api/sibe/settings/public-xlsx-applications",async(request,response)=>{const user=await requireRole(request,response,["sibe"]);if(!user)return;const settings=await loadSystemSettings([WORKFLOW_SETTING_KEYS.publicXlsxRequireEmailVerification]);return response.json({requireEmailVerification:settings.get(WORKFLOW_SETTING_KEYS.publicXlsxRequireEmailVerification)!=="false"});});
publicSimplifiedApplicationsRouter.patch("/api/sibe/settings/public-xlsx-applications",async(request,response)=>{const user=await requireRole(request,response,["sibe"]);if(!user)return;const parsed=settingSchema.safeParse(request.body);if(!parsed.success)return sendValidationError(response,{fieldErrors:parsed.error.flatten().fieldErrors});try{const settings=await loadSystemSettings([WORKFLOW_SETTING_KEYS.publicXlsxRequireEmailVerification]);const old=settings.get(WORKFLOW_SETTING_KEYS.publicXlsxRequireEmailVerification)!=="false";await upsertSystemSettings({[WORKFLOW_SETTING_KEYS.publicXlsxRequireEmailVerification]:String(parsed.data.requireEmailVerification)});await writeAuditLog({user:user.username,userId:user.id,action:"SIBE_PUBLIC_XLSX_EMAIL_VERIFICATION_CHANGED",objectType:"system_setting",objectId:WORKFLOW_SETTING_KEYS.publicXlsxRequireEmailVerification,ipAddress:getRequestIp(request),userAgent:getRequestUserAgent(request),metadata:{old_value:old,new_value:parsed.data.requireEmailVerification,result:"success"}});return response.json(parsed.data);}catch(error){return handleUnexpectedError(response,error,"SIBE_SETTING_UPDATE_FAILED","Die Einstellung konnte nicht gespeichert werden.");}});

publicSimplifiedApplicationsRouter.get("/api/kaskdt/applications",async(request,response)=>{const user=await requireRole(request,response,["kaskdt"]);if(!user)return;const parsed=listSchema.safeParse(request.query);if(!parsed.success)return sendValidationError(response,{fieldErrors:parsed.error.flatten().fieldErrors});try{return response.json(await listKaskdtApplications(parsed.data));}catch(error){return handleUnexpectedError(response,error,"APPLICATION_LIST_FAILED","Die Anträge konnten nicht geladen werden.");}});
publicSimplifiedApplicationsRouter.get("/api/kaskdt/applications/:id",async(request,response)=>{const user=await requireRole(request,response,["kaskdt"]);if(!user)return;if(!z.string().uuid().safeParse(request.params.id).success)return sendError(response,404,"APPLICATION_NOT_FOUND","Der Antrag wurde nicht gefunden.");try{return response.json(await getKaskdtApplication(request.params.id));}catch(error){if(handleKnown(response,error))return;return handleUnexpectedError(response,error,"APPLICATION_DETAIL_FAILED","Der Antrag konnte nicht geladen werden.");}});
publicSimplifiedApplicationsRouter.post("/api/kaskdt/applications/:id/decisions",async(request,response)=>{const user=await requireRole(request,response,["kaskdt"]);if(!user)return;const parsed=decisionSchema.safeParse(request.body);if(!parsed.success)return sendValidationError(response,{fieldErrors:parsed.error.flatten().fieldErrors});try{return response.json(await decideApplicationEntries(user,request.params.id,parsed.data,{ip:getRequestIp(request),userAgent:getRequestUserAgent(request)}));}catch(error){if(handleKnown(response,error))return;if(error instanceof Error&&error.message==="rejection_reason_required")return sendValidationError(response,{fieldErrors:{rejectionReason:["Bitte geben Sie einen Ablehnungsgrund an."]}});return handleUnexpectedError(response,error,"APPLICATION_DECISION_FAILED","Die Entscheidung konnte nicht gespeichert werden.");}});
publicSimplifiedApplicationsRouter.post("/api/kaskdt/applications/:id/finalize",async(request,response)=>{const user=await requireRole(request,response,["kaskdt"]);if(!user)return;const parsed=finalizeSchema.safeParse(request.body);if(!parsed.success)return sendValidationError(response,{fieldErrors:parsed.error.flatten().fieldErrors});try{return response.json(await finalizeApplication(user,request.params.id,parsed.data.applicationVersion,{ip:getRequestIp(request),userAgent:getRequestUserAgent(request)}));}catch(error){if(handleKnown(response,error))return;return handleUnexpectedError(response,error,"APPLICATION_FINALIZE_FAILED","Die Entscheidung konnte nicht abgeschlossen werden.");}});
publicSimplifiedApplicationsRouter.post("/api/kaskdt/applications/:id/retry-mails",async(request,response)=>{const user=await requireRole(request,response,["kaskdt"]);if(!user)return;try{await deliverApplicationMailOutbox(request.params.id);return response.json({message:"Ausstehende E-Mail-Zustellungen wurden erneut verarbeitet."});}catch(error){return handleUnexpectedError(response,error,"APPLICATION_MAIL_RETRY_FAILED","Die E-Mail-Zustellung konnte nicht erneut verarbeitet werden.");}});
