import multer, { MulterError } from "multer";
import sql from "mssql";
import { Router, type Request, type Response } from "express";
import { z } from "zod";
import { normalizeCountryCode } from "../lib/countries";
import { writeAuditLog } from "../lib/auditLog";
import { getPool } from "../lib/db";
import { writeErrorLog } from "../lib/errorLogs";
import { sendSimplifiedRegistrationConfirmation, notifySimplifiedRegistrationNationalitySubscribers } from "../lib/mailRelay";
import { checkRateLimit } from "../lib/rateLimit";
import { buildSimplifiedRegistrationTemplate, parseSimplifiedRegistrationExcel, SimplifiedExcelValidationError } from "../lib/simplifiedRegistrationExcel";
import { approveAllSimplifiedRegistrationEntries, createSimplifiedRegistrationRequest, decideSimplifiedRegistrationEntry, getPublicSimplifiedRegistrationStatus, getSimplifiedRegistrationRequest, listBarracksAreas, listGuardSimplifiedVisitors, listSimplifiedRegistrationRequests, SimplifiedRegistrationConflictError, SimplifiedRegistrationValidationError, updateSimplifiedRegistrationEntry } from "../lib/simplifiedRegistrations";
import { canReviewSimplifiedRegistrations, canViewGuardSimplifiedVisitors, type AuthenticatedUser } from "../lib/visitWorkflow";
import { getRequestIp, getRequestUserAgent, handleUnexpectedError, hasValidCsrfToken, issueCsrfToken, requireAuthenticatedUser, requirePermission, sendError, sendForbidden, sendValidationError } from "./shared";

export const simplifiedRegistrationsRouter = Router();
const upload = multer({ storage: multer.memoryStorage(), limits: { fileSize: 5 * 1024 * 1024, files: 1 } });
const applicantSchema = z.string().trim().email("Bitte eine gültige E-Mail-Adresse des Antragstellers angeben.").max(255);
const statusSchema = z.object({ requestNumber: z.string().trim().min(1).max(32), token: z.string().trim().min(16).max(128) });
const dateOnlySchema = z.string().regex(/^\d{4}-\d{2}-\d{2}$/, "Bitte ein gültiges Datum angeben.");
const entryUpdateSchema = z.object({
  version: z.number().int().positive(), firstName: z.string().trim().min(1).max(120), lastName: z.string().trim().min(1).max(120),
  company: z.string().trim().min(1).max(255), nationalityCode: z.string().trim().transform((value, context) => { const code=normalizeCountryCode(value); if(!code){context.addIssue({code:z.ZodIssueCode.custom,message:"Ungültige Nationalität."});return z.NEVER;}return code; }),
  barracksAreaId: z.string().uuid(), gateId: z.string().uuid().optional().or(z.literal("")), finalValidFrom: dateOnlySchema.optional().or(z.literal("")), finalValidUntil: dateOnlySchema.optional().or(z.literal("")),
  phone:z.string().trim().max(80).optional().or(z.literal("")),email:z.string().trim().email("Besucher-E-Mail ist ungültig.").max(255).optional().or(z.literal("")),
  visitorStreet:z.string().trim().max(255).optional().or(z.literal("")),visitorHouseNumber:z.string().trim().max(40).optional().or(z.literal("")),visitorPostalCode:z.string().trim().max(20).optional().or(z.literal("")),visitorCity:z.string().trim().max(120).optional().or(z.literal("")),
  idDocumentType:z.string().trim().max(40).optional().or(z.literal("")),idDocumentValidUntil:dateOnlySchema.optional().or(z.literal("")),idDocumentNumber:z.string().trim().max(120).optional().or(z.literal("")),
  rejectionReason:z.string().trim().max(1000).optional().or(z.literal("")),licensePlate:z.string().trim().max(40).optional().or(z.literal("")),hostName:z.string().trim().max(255).optional().or(z.literal("")),hostPhone:z.string().trim().max(80).optional().or(z.literal("")),hostEmail:z.string().trim().email("Ansprechpartner-E-Mail ist ungültig.").max(255).optional().or(z.literal("")),hostDepartment:z.string().trim().max(255).optional().or(z.literal("")),purpose:z.string().trim().max(500).optional().or(z.literal("")),notes:z.string().trim().max(4000).optional().or(z.literal(""))
}).superRefine((value,context)=>{if(Boolean(value.finalValidFrom)!==Boolean(value.finalValidUntil))context.addIssue({code:z.ZodIssueCode.custom,path:[value.finalValidFrom?"finalValidUntil":"finalValidFrom"],message:"Beide endgültigen Datumsfelder müssen gemeinsam gesetzt werden."});if(value.finalValidFrom&&value.finalValidUntil&&value.finalValidUntil<value.finalValidFrom)context.addIssue({code:z.ZodIssueCode.custom,path:["finalValidUntil"],message:"Gültig bis darf nicht vor Gültig von liegen."});});
const decisionSchema=z.object({version:z.number().int().positive(),finalValidFrom:dateOnlySchema.optional(),finalValidUntil:dateOnlySchema.optional(),rejectionReason:z.string().trim().max(1000).optional()}).superRefine((value,context)=>{if(value.finalValidFrom&&value.finalValidUntil&&value.finalValidUntil<value.finalValidFrom)context.addIssue({code:z.ZodIssueCode.custom,path:["finalValidUntil"],message:"Gültig bis darf nicht vor Gültig von liegen."});});
const approveAllSchema=z.object({confirmProposedDates:z.literal(true)});
const areaSchema=z.object({name:z.string().trim().min(1).max(120),description:z.string().trim().max(500).optional().or(z.literal("")),isActive:z.boolean().optional(),sortOrder:z.number().int().min(0).max(10000).optional()});

function rateLimit(request:Request,response:Response,kind:string,limit=30){const decision=checkRateLimit(`${kind}:${getRequestIp(request)}`,limit,60);if(decision.allowed)return true;response.setHeader("Retry-After",String(decision.retryAfterSeconds));response.status(429).json({error:"RATE_LIMITED",message:"Zu viele Anfragen. Bitte später erneut versuchen.",retryAfterSeconds:decision.retryAfterSeconds});return false;}
function requireCsrf(request:Request,response:Response){if(hasValidCsrfToken(request))return true;sendError(response,403,"CSRF_INVALID","Sicherheitsprüfung fehlgeschlagen. Bitte laden Sie die Seite neu.");return false;}
async function requireReviewer(request:Request,response:Response):Promise<AuthenticatedUser|null>{const user=await requireAuthenticatedUser(request,response);if(!user)return null;if(canReviewSimplifiedRegistrations(user))return user;sendForbidden(response);return null;}
async function requireGuardViewer(request:Request,response:Response):Promise<AuthenticatedUser|null>{const user=await requireAuthenticatedUser(request,response);if(!user)return null;if(canViewGuardSimplifiedVisitors(user))return user;sendForbidden(response);return null;}
function domainError(response:Response,error:unknown){if(error instanceof SimplifiedRegistrationConflictError)return sendError(response,409,"VERSION_CONFLICT","Der Datensatz wurde zwischenzeitlich geändert. Bitte neu laden.");if(error instanceof SimplifiedExcelValidationError)return sendValidationError(response,{fieldErrors:{file:error.messages}});if(error instanceof SimplifiedRegistrationValidationError)return sendError(response,400,"VALIDATION_ERROR",error.messages.join(" "),{messages:error.messages});return null;}

simplifiedRegistrationsRouter.get("/api/public/simplified-registration/bootstrap",async(_request,response)=>{try{const [areas,csrfToken]=await Promise.all([listBarracksAreas(false),issueCsrfToken(response)]);response.json({areas,csrfToken});}catch(error){handleUnexpectedError(response,error,"DATABASE_ERROR","Die vereinfachte Anmeldung konnte nicht geladen werden.");}});
simplifiedRegistrationsRouter.get("/api/public/simplified-registration/template",async(_request,response)=>{try{const buffer=await buildSimplifiedRegistrationTemplate();response.setHeader("Content-Type","application/vnd.openxmlformats-officedocument.spreadsheetml.sheet");response.setHeader("Content-Disposition",'attachment; filename="vereinfachte-besucheranmeldung.xlsx"');response.send(buffer);}catch(error){handleUnexpectedError(response,error,"TEMPLATE_ERROR","Die Excel-Vorlage konnte nicht erstellt werden.");}});
simplifiedRegistrationsRouter.post("/api/public/simplified-registration/import",(request,response)=>{if(!rateLimit(request,response,"public-simplified-import",10)||!requireCsrf(request,response))return;upload.single("file")(request,response,async(error)=>{if(error){return sendError(response,400,error instanceof MulterError&&error.code==="LIMIT_FILE_SIZE"?"FILE_TOO_LARGE":"UPLOAD_ERROR",error instanceof MulterError&&error.code==="LIMIT_FILE_SIZE"?"Die Excel-Datei ist größer als 5 MB.":"Die Excel-Datei konnte nicht gelesen werden.");}const applicant=applicantSchema.safeParse(request.body?.applicantEmail);if(!applicant.success)return sendValidationError(response,applicant.error.flatten());const file=request.file;const allowedMimeTypes=new Set(["application/vnd.openxmlformats-officedocument.spreadsheetml.sheet","application/octet-stream"]);if(!file||!file.originalname.toLowerCase().endsWith(".xlsx")||!allowedMimeTypes.has(file.mimetype))return sendValidationError(response,{fieldErrors:{file:["Bitte ausschließlich eine XLSX-Datei auswählen."]}});try{const rows=await parseSimplifiedRegistrationExcel(file.buffer);const created=await createSimplifiedRegistrationRequest(rows,{applicantEmail:applicant.data,sourceFilename:file.originalname,ipAddress:getRequestIp(request),userAgent:getRequestUserAgent(request)});void sendSimplifiedRegistrationConfirmation({to:applicant.data,requestNumber:created.requestNumber,token:created.token,visitorCount:created.entries.length}).catch(async(mailError)=>writeErrorLog({level:"warning",errorCode:"SIMPLIFIED_CONFIRMATION_MAIL_FAILED",message:"Bestätigung der vereinfachten Anmeldung konnte nicht versendet werden.",stackTrace:mailError instanceof Error?mailError.stack??null:null,metadataJson:JSON.stringify({requestId:created.requestId})}));for(const entry of created.entries)void notifySimplifiedRegistrationNationalitySubscribers({...entry,requestNumber:created.requestNumber});return response.status(201).json({message:"Vereinfachte Besucheranmeldung wurde eingereicht.",requestNumber:created.requestNumber,token:created.token,visitorCount:created.entries.length,status:"pending",statusUrl:"/vereinfachte-besucheranmeldung/status"});}catch(importError){const handled=domainError(response,importError);if(handled)return handled;return handleUnexpectedError(response,importError,"SIMPLIFIED_IMPORT_ERROR","Die vereinfachte Besucheranmeldung konnte nicht importiert werden.");}});});
simplifiedRegistrationsRouter.post("/api/public/simplified-registration/status",async(request,response)=>{if(!rateLimit(request,response,"public-simplified-status",20)||!requireCsrf(request,response))return;const parsed=statusSchema.safeParse(request.body);if(!parsed.success)return sendValidationError(response,parsed.error.flatten());try{const result=await getPublicSimplifiedRegistrationStatus(parsed.data.requestNumber,parsed.data.token);if(!result)return sendError(response,404,"NOT_FOUND","Vorgangsnummer oder Sicherheitstoken ist ungültig.");return response.json(result);}catch(error){return handleUnexpectedError(response,error,"DATABASE_ERROR","Der Status konnte nicht geladen werden.");}});

simplifiedRegistrationsRouter.get("/api/kaskdt/simplified-registrations",async(request,response)=>{if(!await requireReviewer(request,response))return;try{return response.json({requests:await listSimplifiedRegistrationRequests(typeof request.query.status==="string"?request.query.status:undefined)});}catch(error){return handleUnexpectedError(response,error,"DATABASE_ERROR","Vorgänge konnten nicht geladen werden.");}});
simplifiedRegistrationsRouter.get("/api/kaskdt/simplified-registrations/:id",async(request,response)=>{if(!await requireReviewer(request,response))return;try{const item=await getSimplifiedRegistrationRequest(request.params.id);return item?response.json(item):sendError(response,404,"NOT_FOUND","Vorgang nicht gefunden.");}catch(error){return handleUnexpectedError(response,error,"DATABASE_ERROR","Vorgang konnte nicht geladen werden.");}});
simplifiedRegistrationsRouter.patch("/api/kaskdt/simplified-registrations/:id/entries/:entryId",async(request,response)=>{const user=await requireReviewer(request,response);if(!user)return;const parsed=entryUpdateSchema.safeParse(request.body);if(!parsed.success)return sendValidationError(response,parsed.error.flatten());try{const result=await updateSimplifiedRegistrationEntry(user,request.params.id,request.params.entryId,parsed.data);return result?response.json(result):sendError(response,404,"NOT_FOUND","Eintrag nicht gefunden.");}catch(error){const handled=domainError(response,error);return handled||handleUnexpectedError(response,error,"DATABASE_ERROR","Eintrag konnte nicht gespeichert werden.");}});
for(const action of ["approve","reject","revoke"] as const)simplifiedRegistrationsRouter.post(`/api/kaskdt/simplified-registrations/:id/entries/:entryId/${action}`,async(request,response)=>{const user=await requireReviewer(request,response);if(!user)return;const parsed=decisionSchema.safeParse(request.body);if(!parsed.success)return sendValidationError(response,parsed.error.flatten());try{const result=await decideSimplifiedRegistrationEntry(user,request.params.id,request.params.entryId,action,parsed.data);return result?response.json(result):sendError(response,404,"NOT_FOUND","Eintrag nicht gefunden.");}catch(error){const handled=domainError(response,error);return handled||handleUnexpectedError(response,error,"DATABASE_ERROR","Entscheidung konnte nicht gespeichert werden.");}});
simplifiedRegistrationsRouter.post("/api/kaskdt/simplified-registrations/:id/approve-all",async(request,response)=>{const user=await requireReviewer(request,response);if(!user)return;const parsed=approveAllSchema.safeParse(request.body);if(!parsed.success)return sendValidationError(response,parsed.error.flatten());try{return response.json(await approveAllSimplifiedRegistrationEntries(user,request.params.id));}catch(error){return handleUnexpectedError(response,error,"DATABASE_ERROR","Sammelgenehmigung konnte nicht gespeichert werden.");}});

simplifiedRegistrationsRouter.get("/api/guard/simplified-visitors",async(request,response)=>{const user=await requireGuardViewer(request,response);if(!user)return;try{return response.json({entries:await listGuardSimplifiedVisitors(user,{search:typeof request.query.search==="string"?request.query.search:undefined,validity:typeof request.query.validity==="string"?request.query.validity:undefined})});}catch(error){const handled=domainError(response,error);return handled||handleUnexpectedError(response,error,"DATABASE_ERROR","Vereinfachte Besucher konnten nicht geladen werden.");}});

simplifiedRegistrationsRouter.get("/api/admin/barracks-areas",async(request,response)=>{if(!await requirePermission(request,response,"admin.guards"))return;try{return response.json({areas:await listBarracksAreas(true)});}catch(error){return handleUnexpectedError(response,error,"DATABASE_ERROR","Kasernenbereiche konnten nicht geladen werden.");}});
simplifiedRegistrationsRouter.post("/api/admin/barracks-areas",async(request,response)=>{const user=await requirePermission(request,response,"admin.guards");if(!user)return;const parsed=areaSchema.safeParse(request.body);if(!parsed.success)return sendValidationError(response,parsed.error.flatten());try{const created=await (await getPool()).request().input("name",sql.NVarChar(120),parsed.data.name).input("description",sql.NVarChar(500),parsed.data.description||null).input("active",sql.Bit,parsed.data.isActive??true).input("sort",sql.Int,parsed.data.sortOrder??100).query<{id:string}>("INSERT INTO dbo.barracks_areas(name,description,is_active,sort_order) OUTPUT inserted.id VALUES(@name,@description,@active,@sort)");const id=created.recordset[0].id;await writeAuditLog({user:user.username,userId:user.id,action:"BARRACKS_AREA_CREATED",objectType:"barracks_area",objectId:id,metadata:{name:parsed.data.name}});return response.status(201).json({id});}catch(error){return handleUnexpectedError(response,error,"DATABASE_ERROR","Kasernenbereich konnte nicht gespeichert werden.");}});
simplifiedRegistrationsRouter.patch("/api/admin/barracks-areas/:id",async(request,response)=>{const user=await requirePermission(request,response,"admin.guards");if(!user)return;const parsed=areaSchema.partial().safeParse(request.body);if(!parsed.success)return sendValidationError(response,parsed.error.flatten());try{const changed=await (await getPool()).request().input("id",sql.UniqueIdentifier,request.params.id).input("name",sql.NVarChar(120),parsed.data.name??null).input("description",sql.NVarChar(500),parsed.data.description??null).input("active",sql.Bit,parsed.data.isActive??null).input("sort",sql.Int,parsed.data.sortOrder??null).query("UPDATE dbo.barracks_areas SET name=COALESCE(@name,name),description=CASE WHEN @description IS NULL THEN description ELSE @description END,is_active=COALESCE(@active,is_active),sort_order=COALESCE(@sort,sort_order),updated_at=SYSUTCDATETIME() WHERE id=@id");if(!changed.rowsAffected[0])return sendError(response,404,"NOT_FOUND","Kasernenbereich nicht gefunden.");await writeAuditLog({user:user.username,userId:user.id,action:"BARRACKS_AREA_UPDATED",objectType:"barracks_area",objectId:request.params.id,metadata:{changedFields:Object.keys(parsed.data)}});return response.json({success:true});}catch(error){return handleUnexpectedError(response,error,"DATABASE_ERROR","Kasernenbereich konnte nicht gespeichert werden.");}});
simplifiedRegistrationsRouter.delete("/api/admin/barracks-areas/:id",async(request,response)=>{const user=await requirePermission(request,response,"admin.guards");if(!user)return;try{const linked=await (await getPool()).request().input("id",sql.UniqueIdentifier,request.params.id).query<{count:number}>("SELECT (SELECT COUNT(*) FROM dbo.gates WHERE barracks_area_id=@id)+(SELECT COUNT(*) FROM dbo.simplified_registration_entries WHERE barracks_area_id=@id) AS count");if((linked.recordset[0]?.count??0)>0)return sendError(response,409,"CONFLICT","Kasernenbereich wird noch von Wachen oder Anmeldungen verwendet.");const deleted=await (await getPool()).request().input("id",sql.UniqueIdentifier,request.params.id).query("DELETE FROM dbo.barracks_areas WHERE id=@id");if(!deleted.rowsAffected[0])return sendError(response,404,"NOT_FOUND","Kasernenbereich nicht gefunden.");await writeAuditLog({user:user.username,userId:user.id,action:"BARRACKS_AREA_DELETED",objectType:"barracks_area",objectId:request.params.id});return response.json({success:true});}catch(error){return handleUnexpectedError(response,error,"DATABASE_ERROR","Kasernenbereich konnte nicht gelöscht werden.");}});
